name: Deploy PKP Project to VPS

on:
  workflow_call:
    inputs:
      project:
        description: "The PKP project name (e.g., ojs, omp, ops)"
        required: true
        type: string
      branch:
        description: "The branch name to deploy"
        required: true
        type: string
      pr_number:
        description: "PR Number for fork deployments (optional)"
        required: false
        type: string # Changed to string to avoid validation issues with passed values
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      SSH_HOST:
        required: true
      SSH_USERNAME:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_HOST: ${{ secrets.SSH_HOST }} # Map secret to env for conditional check
    steps:
      - name: Detect base branch
        if: ${{ !inputs.pr_number }}
        id: detect-base
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const possibleBases = ['stable-3_3_0', 'stable-3_4_0', 'stable-3_5_0', 'main'];
            if (possibleBases.includes('${{ inputs.branch }}')) {
              return '${{ inputs.branch }}';
            }
            let minAhead = Infinity;
            let selectedBase = null;
            for (const base of possibleBases) {
              try {
                const response = await github.rest.repos.compareCommits({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  base,
                  head: '${{ inputs.branch }}'
                });
                const { status, ahead_by, behind_by } = response.data;
                if (status === 'ahead' && behind_by === 0 && ahead_by < minAhead) {
                  minAhead = ahead_by;
                  selectedBase = base;
                }
              } catch (e) {
                // Skip if error (e.g., base does not exist)
              }
            }
            if (selectedBase) {
              return selectedBase;
            } else {
              throw new Error('Could not detect base branch for ${{ inputs.branch }}');
      - name: Fetch PR details
        if: ${{ inputs.pr_number }}
        id: fetch-pr
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: Number('${{ inputs.pr_number }}')  // Cast to number for API
            });
            return JSON.stringify({
              head_owner: pr.data.head.repo.owner.login,
              head_branch: pr.data.head.ref,
              base_branch: pr.data.base.ref
            });
      - name: Deploy via SSH
        if: ${{ env.SSH_HOST != '' }} # Skip if secret is empty/missing
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            project="${{ inputs.project }}"
            branch="${{ inputs.pr_number && format('pr-{0}', inputs.pr_number) || inputs.branch }}"
            base_branch="${{ inputs.pr_number && fromJSON(steps.fetch-pr.outputs.result).base_branch || steps.detect-base.outputs.result }}"
            clone_owner="${{ inputs.pr_number && fromJSON(steps.fetch-pr.outputs.result).head_owner || github.repository_owner }}"
            clone_branch="${{ inputs.pr_number && fromJSON(steps.fetch-pr.outputs.result).head_branch || inputs.branch }}"
            base="/var/www/${{ secrets.SSH_HOST }}.sslip.io/$project"
            dir="$base/$branch"
            tmp_dir="$base/${branch}_tmp"

            # Clean up any previous temp dir to avoid conflicts
            rm -rf "$tmp_dir"

            # Clone fresh into temp dir
            git clone \
              --depth 1 \
              --single-branch \
              --branch "$clone_branch" \
              --recurse-submodules \
              --shallow-submodules \
              --filter=blob:none \
              https://github.com/$clone_owner/$project.git "$tmp_dir"

            cd "$tmp_dir"

            # Copy template and update config
            cp config.TEMPLATE.inc.php config.inc.php

            # Extract MySQL root password
            PASSWORD=$(grep 'mysql_root_pass=' /root/.hcloud_password | sed 's/.*="//;s/"$//')

            # Update database settings in [database] section
            sed -i '/^\[database\]$/,/^\[/ s/^username = .*/username = root/' config.inc.php
            sed -i '/^\[database\]$/,/^\[/ s/^password = .*/password = "'"$PASSWORD"'"/' config.inc.php
            sed -i '/^\[database\]$/,/^\[/ s/^name = .*/name = '"${project}_${base_branch}"'/' config.inc.php

            # Update installed flag in [general] section
            sed -i '/^\[general\]$/,/^\[/ s/^installed = .*/installed = On/' config.inc.php

            # Install dependencies
            composer --working-dir=lib/pkp install
            composer --working-dir=plugins/generic/citationStyleLanguage install
            composer --working-dir=plugins/paymethod/paypal install

            # Generate app key
            php lib/pkp/tools/appKey.php generate

            npm install
            npm run build

            # Prepare persistent directories
            mkdir files
            # public exists from git clone; we'll handle it below

            if [ -d "$dir" ]; then
              # Move files (replace entirely, as it's user-generated)
              rm -rf files
              mv "$dir/files" files

              # Move public (replace git version with old version to preserve uploads)
              rm -rf public
              mv "$dir/public" public

              # Remove the now-partially-emptied old dir
              rm -rf "$dir"
            fi

            # Move the temp dir to the live dir
            mv "$tmp_dir" "$dir"

            # Set permissions
            chown -R deploy:www-data "$dir"
            chmod -R 775 "$dir"
