name: Deploy PKP Project to VPS

on:
  workflow_call:
    inputs:
      project:
        description: "The PKP project name (e.g., ojs, omp, ops)"
        required: true
        type: string
      branch:
        description: "The branch name to deploy"
        required: false
        type: string
      pr_number:
        description: "PR Number for fork deployments (optional)"
        required: false
        type: string
      tag:
        description: "Tag name to deploy from main PKP repo (e.g., 'ojs-3_5_0-1') (optional, overrides branch/pr_number)"
        required: false
        type: string
      copies:
        description: "Comma-separated suffixes for additional branch copies (e.g., 'qa,hosting')"
        required: false
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      SSH_HOST:
        required: true
      SSH_USERNAME:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_HOST: ${{ secrets.SSH_HOST }} # Map secret to env for conditional check
    steps:
      - name: Fetch PR details
        if: ${{ inputs.pr_number }}
        id: fetch-pr
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: Number('${{ inputs.pr_number }}')
            });
            return JSON.stringify({
              head_owner: pr.data.head.repo.owner.login,
              head_branch: pr.data.head.ref,
              base_branch: pr.data.base.ref
            });
      - name: Deploy via SSH
        if: ${{ env.SSH_HOST != '' }} # Skip if secret is empty/missing
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            project="${{ inputs.project }}"
            tag="${{ inputs.tag }}"
            pr_number="${{ inputs.pr_number }}"
            input_branch="${{ inputs.branch }}"  # Save original branch input

            if [ -n "$tag" ]; then
              clone_owner="pkp"
              clone_branch="$tag"
              base_branch="$tag"  # Use tag for DB naming
              branch="$tag"  # Use tag as directory name
              do_import=1  # Import dataset like PR

              # Determine dataset_branch for tags
              version="$tag"
              if [[ "$tag" == "${project}-"* ]]; then
                version="${tag#${project}-}"
              fi
              dataset_branch="stable-${version%%-*}"
            elif [ -n "$pr_number" ]; then
              branch="pr-$pr_number"
              base_branch="${{ inputs.pr_number && fromJSON(steps.fetch-pr.outputs.result).base_branch || inputs.branch }}"
              dataset_branch="$base_branch"  # Use base_branch for dataset
              clone_owner="${{ inputs.pr_number && fromJSON(steps.fetch-pr.outputs.result).head_owner || github.repository_owner }}"
              clone_branch="${{ inputs.pr_number && fromJSON(steps.fetch-pr.outputs.result).head_branch || inputs.branch }}"
              do_import=1  # Import dataset
            else
              branch="$input_branch"
              base_branch="$input_branch"  # Assume stable branch
              dataset_branch="$base_branch"  # Use branch for dataset
              clone_owner="${{ github.repository_owner }}"
              clone_branch="$input_branch"
              do_import=0  # No import for regular branches
            fi

            # Sanitize base_branch for DB name (replace dashes with underscores)
            db_safe_base="${base_branch//-/_}"

            copies="${{ inputs.copies }}"

            # Set suffixes (default empty for main copy; add others if copies provided and not PR/tag)
            suffixes=("")
            if [ $do_import -eq 0 ] && [ -n "$copies" ]; then
              IFS=',' read -r -a additional <<< "$copies"
              suffixes+=("${additional[@]}")
            fi

            # Extract MySQL root password (once)
            PASSWORD=$(grep 'mysql_root_pass=' /root/.hcloud_password | sed 's/.*="//;s/"$//')

            # Build once for efficiency (composer and npm)
            build_dir="/tmp/build_${project}_${branch//[^a-zA-Z0-9]/_}"
            rm -rf "$build_dir"

            git clone \
              --depth 1 \
              --single-branch \
              --branch "$clone_branch" \
              --recurse-submodules \
              --shallow-submodules \
              --filter=blob:none \
              https://github.com/$clone_owner/$project.git "$build_dir"

            cd "$build_dir"

            # Install dependencies (no config needed yet)
            composer --working-dir=lib/pkp install
            composer --working-dir=plugins/generic/citationStyleLanguage install
            composer --working-dir=plugins/paymethod/paypal install

            npm install
            npm run build

            # Clean up unnecessary directories to reduce copy size/time
            rm -rf .git node_modules

            # Loop over suffixes to deploy each copy
            for suffix in "${suffixes[@]}"; do
              if [ -z "$suffix" ]; then
                variant="$project"
                db_variant="$db_safe_base"
              else
                variant="${project}-${suffix}"
                db_variant="${suffix}_${db_safe_base}"
              fi

              db_name="${project}_${db_variant}"
              base="/var/www/${{ secrets.SSH_HOST }}.sslip.io/$variant"
              dir="$base/$branch"
              tmp_dir="$base/${branch}_tmp"

              # Ensure base directory exists
              mkdir -p "$base"

              # Clean up previous temp dir
              rm -rf "$tmp_dir"

              cp -r "$build_dir" "$tmp_dir"
              cd "$tmp_dir"

              # Copy and update config (per copy)
              cp config.TEMPLATE.inc.php config.inc.php

              sed -i '/^\[database\]$/,/^\[/ s/^username = .*/username = root/' config.inc.php
              sed -i '/^\[database\]$/,/^\[/ s/^password = .*/password = "'"$PASSWORD"'"/' config.inc.php
              sed -i '/^\[database\]$/,/^\[/ s/^name = .*/name = '"$db_name"'/' config.inc.php

              sed -i '/^\[general\]$/,/^\[/ s/^installed = .*/installed = On/' config.inc.php

              # Prepare persistent directories
              mkdir -p files public

              if [ $do_import -eq 1 ]; then
                dataset_tmp="/tmp/datasets_${variant}_${branch//[^a-zA-Z0-9]/_}"
                rm -rf "$dataset_tmp"

                git clone \
                  --depth 1 \
                  --filter=blob:none \
                  --sparse \
                  https://github.com/pkp/datasets.git "$dataset_tmp"

                cd "$dataset_tmp"
                git sparse-checkout set $project/$dataset_branch/mysql

                # Drop DB if exists, create fresh
                mysql -u root -p"$PASSWORD" -h localhost -P 3306 -e "DROP DATABASE IF EXISTS $db_name; CREATE DATABASE $db_name CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;"

                # Load SQL
                mysql -u root -p"$PASSWORD" -h localhost -P 3306 "$db_name" < "$dataset_tmp/$project/$dataset_branch/mysql/database.sql"

                # Reset and copy fresh files/public from dataset
                rm -rf files public
                cp -r "$dataset_tmp/$project/$dataset_branch/mysql/files" files
                cp -r "$dataset_tmp/$project/$dataset_branch/mysql/public" public

                chown -R deploy:www-data files public
                chmod -R 775 files public

                rm -rf "$dataset_tmp"

                cd "$tmp_dir"
              else
                # For branches, preserve files/public if dir exists
                if [ -d "$dir" ]; then
                  rm -rf files
                  mv "$dir/files" files
                  rm -rf public
                  mv "$dir/public" public
                fi
              fi

              # Generate app key (instance-specific, after config and DB setup)
              php lib/pkp/tools/appKey.php generate

              # Now minimize downtime: delete old dir (if any) and move temp to live
              rm -rf "$dir"
              mv "$tmp_dir" "$dir"

              # Set permissions on entire dir
              chown -R deploy:www-data "$dir"
              chmod -R 775 "$dir"
            done

            # Clean up build dir
            rm -rf "$build_dir"
