name: Update PKP Dataset on VPS

on:
  workflow_call:
    inputs:
      project:
        description: "The PKP project name (e.g., ojs, omp, ops)"
        required: true
        type: string
      branch:
        description: "The branch name to update dataset for"
        required: true
        type: string
      copies:
        description: "Comma-separated list of copies to update (e.g., 'default,qa,hosting'); 'default' for the one without suffix"
        required: true
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      SSH_HOST:
        required: true
      SSH_USERNAME:
        required: true

jobs:
  update-dataset:
    runs-on: ubuntu-latest
    env:
      SSH_HOST: ${{ secrets.SSH_HOST }} # Map secret to env for conditional check
    steps:
      - name: Update Dataset via SSH
        if: ${{ env.SSH_HOST != '' }} # Skip if secret is empty/missing
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            project="${{ inputs.project }}"
            branch="${{ inputs.branch }}"
            copies="${{ inputs.copies }}"

            # Sanitize branch for DB name (replace dashes with underscores, matching deployment logic)
            db_safe_branch="${branch//-/_}"

            # Set suffixes from required copies input
            IFS=',' read -r -a suffixes <<< "$copies"

            # Extract MySQL root password (once)
            PASSWORD=$(grep 'mysql_root_pass=' /root/.hcloud_password | sed 's/.*="//;s/"$//')

            # Clone sparse dataset once
            tmp_dir="/tmp/datasets_${project}_${branch//[^a-zA-Z0-9]/_}"
            rm -rf "$tmp_dir"

            git clone \
              --depth 1 \
              --filter=blob:none \
              --sparse \
              https://github.com/pkp/datasets.git "$tmp_dir"

            cd "$tmp_dir"
            git sparse-checkout set $project/$branch/mysql

            dataset_path="$tmp_dir/$project/$branch/mysql"

            # Loop over suffixes to update each copy
            for suffix in "${suffixes[@]}"; do
              if [ "$suffix" == "default" ]; then
                variant="$project"
                db_variant="$db_safe_branch"
              else
                variant="${project}-${suffix}"
                db_variant="${suffix}_${db_safe_branch}"
              fi

              db_name="${project}_${db_variant}"
              base="/var/www/${{ secrets.SSH_HOST }}.sslip.io/$variant"
              app_dir="$base/$branch"

              # Drop and recreate database
              mysql -u root -p"$PASSWORD" -h localhost -P 3306 -e "DROP DATABASE IF EXISTS $db_name; CREATE DATABASE $db_name CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;"

              # Load dataset into database
              mysql -u root -p"$PASSWORD" -h localhost -P 3306 "$db_name" < "$dataset_path/database.sql"

              # Copy files and public from dataset (replace existing)
              rm -rf "$app_dir/files" "$app_dir/public"
              cp -r "$dataset_path/files" "$app_dir/files"
              cp -r "$dataset_path/public" "$app_dir/public"


              # Set permissions (matching deployment: use deploy:www-data for consistency)
              chown -R www-data:www-data "$app_dir/files" "$app_dir/public" "$app_dir/status.php"
              chmod -R 775 "$app_dir/files" "$app_dir/public" "$app_dir/status.php"
            done

            # Clean up temp dir
            rm -rf "$tmp_dir"
